# Generated by Django 5.0.7 on 2024-07-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Cursos',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Estudiantes',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Profesores',
        ),
    ]
