# Generated by Django 5.0.7 on 2024-07-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_curso_cursos_rename_estudiante_estudiantes_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cursos',
            table='Cursos',
        ),
    ]
