# Generated by Django 5.0.7 on 2024-07-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cursos_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Estudiante',
        ),
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Profesor',
        ),
        migrations.AlterModelTable(
            name='curso',
            table=None,
        ),
    ]
